services:
  - type: web
    name: smart_lms
    env: python
    region: oregon
    plan: free
    workDir: .
    buildCommand: 
        pip install -r requirements.txt
        python smart_lms/manage.py migrate 
    startCommand: gunicorn smart_lms.smart_lms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smart_lms.smart_lms.settings
      - key: PYTHONPATH
        value: .
    buildFilter:
      paths:
        - smart_lms/**
        - requirements.txt
        - render.yaml

  - type: web
    name: smart-lms-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd smart-lms-frontend && npm install && npm run build && cp public/_redirects dist/
    staticPublishPath: ./smart-lms-frontend/dist
    buildFilter:
      paths:
        - smart-lms-frontend/**
        - render.yaml
