# Generated by Django 5.2 on 2025-05-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
